# Generated by Django 3.1.1 on 2020-12-18 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_auto_20201217_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='number1',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='number2',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
