# Generated by Django 3.1.1 on 2020-12-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20201218_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='number1',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='number2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
