# Generated by Django 3.1.1 on 2020-12-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20201219_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='number1',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='number2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
