# Generated by Django 3.1.1 on 2020-12-27 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20201219_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_full_name', models.CharField(max_length=120)),
                ('s_number1', models.IntegerField()),
                ('s_number2', models.IntegerField(blank=True, null=True)),
                ('s_address1', models.CharField(max_length=120, null=True)),
                ('s_address2', models.CharField(max_length=120, null=True)),
                ('s_city', models.CharField(max_length=50, null=True)),
                ('s_state', models.CharField(max_length=50, null=True)),
                ('s_zip', models.IntegerField(null=True)),
                ('s_country', models.CharField(max_length=50, null=True)),
                ('r_full_name', models.CharField(max_length=120)),
                ('r_number1', models.IntegerField()),
                ('r_number2', models.IntegerField(blank=True, null=True)),
                ('r_address1', models.CharField(max_length=120, null=True)),
                ('r_address2', models.CharField(max_length=120, null=True)),
                ('r_city', models.CharField(max_length=50, null=True)),
                ('r_state', models.CharField(max_length=50, null=True)),
                ('r_zip', models.IntegerField(null=True)),
                ('r_country', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 27, 7, 55, 19, 690637, tzinfo=utc))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
