# Generated by Django 3.1.1 on 2020-12-27 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_parceldelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldelivery',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 11, 29, 3, 338415, tzinfo=utc)),
        ),
    ]
