# Generated by Django 3.1.1 on 2020-12-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201227_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceldelivery',
            name='time',
        ),
    ]
