# Generated by Django 3.1.1 on 2020-12-28 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0012_parceldelivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldelivery',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 10, 4, 10, 150810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parceldelivery',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
