# Generated by Django 3.1.1 on 2020-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201228_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldelivery',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
