# Generated by Django 3.1.1 on 2021-04-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_auto_20201228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceldelivery',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='height',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='status',
            field=models.CharField(choices=[('1', 'Request Sent'), ('2', 'Request Accepted'), ('3', 'Request Declined'), ('4', 'Delivery Pending'), ('5', 'Delivery Canceled'), ('6', 'Delivered')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='weight',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='width',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.friend'),
        ),
    ]
